name: dependabot

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    uses: ./.github/workflows/merge-dependabot-prs.yml
    with:
      only-patch: false
